<a href="https://colab.research.google.com/github/Nlasry1996/Nautica-Home/blob/main/OneHotEncoder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
! git clone https://github.com/Nlasry1996/Nautica-Home.git # Connect to Github

fatal: destination path 'Nautica-Home' already exists and is not an empty directory.

In [16]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
import numpy as np
df=pd.read_csv('/content/Nautica-Home/NHDataset - NHDataset.csv')
# Assuming your dataset is stored in a DataFrame called 'df'
encoder = OneHotEncoder(sparse=False)

# Fit and transform the City column
city_encoded = encoder.fit_transform(df[['City']])

# Fit and transform the District column
district_encoded = encoder.fit_transform(df[['District']])

# Concatenate the encoded columns back to the DataFrame
df_encoded = pd.concat([df, pd.DataFrame(city_encoded), pd.DataFrame(district_encoded)], axis=1)

df_encoded

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(
/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,Order_Date,Customer_ID,Order_ID,Quantity,City,District,Catalog_Number,Hebrew_Description,English_Description,Added_Date,...,248,249,250,0,1,2,3,4,5,6
0,4/3/2022,100110,SO22000098,1,Ir ha-Karmel,חיפה,NHD1001-15-2,ינג כחול כיסוי 100% כותנה במילוי מיקרופייבר 40...,400GSM PREMIUM MICROFIBER BLANKET BLUE PIPING 15,5/31/2021,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,4/3/2022,100110,SO22000098,3,Ir ha-Karmel,חיפה,NHD1002-15-2,שמיכת פוך פייפינג כיסוי 100% כותנה מיקרופייבר ...,600GSM PREMIUM MICROFIBER BLANKET BLUE PIPING 15,5/31/2021,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,4/3/2022,100110,SO22000098,1,Ir ha-Karmel,חיפה,NHT3004-15-16,מגבת גוף אפור כהה 100% כותנה 600 גר' 90/150,Body towel 100% cotton Aqua Fibro 600 gsm 90x150,5/31/2021,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,4/3/2022,100110,SO22000098,1,Ir ha-Karmel,חיפה,NHT3005-15-26,מגבת גוף טורקיז 100% כותנה 600 גר' 90/150,Body towel 100% cotton Aqua Fibro 600 gsm 90x150,5/31/2021,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,4/3/2022,100110,SO22000098,1,Ir ha-Karmel,חיפה,NHT3006-15-23,מגבת פסים 150X90 כחול 600 גר',STRIPE TOWEL 150X90 BLUE 600 GSM,12/15/2021,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9156,4/30/2023,103230,SO23001622,1,Ashdod,דרום,NLW-71002M8,OCEAN M Mix&Match women tank,"Mix&Match women tank,,M",11/10/2021,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
9157,4/30/2023,103230,SO23001622,1,Ashdod,דרום,NLW-71003L6,-PEACH-L-Mix&Match women shorts,NaN,10/27/2021,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
9158,4/30/2023,103230,SO23001622,1,Ashdod,דרום,NLW-71003L8,-OCEAN-L-Mix&Match women shorts,NaN,10/27/2021,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
9159,4/30/2023,103231,SO23001624,1,Kiryat-Motzkin,חיפה,NHB1006-16-13,"סט 100% כותנה סטן 220 160 סמ BASIC L. BLUE""",NaN,3/1/2022,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
9160,4/30/2023,103231,SO23001624,1,Kiryat-Motzkin,חיפה,NHB1007-16-11,"סט 100% כותנה סטן 220 160 סמ BASIC SAND""",NaN,3/1/2022,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [17]:
df_encoded['Order_Date'] = pd.to_datetime(df_encoded['Order_Date']) # Convert 'Order_Date' to a datetime format.
df_encoded['Month'] = df_encoded['Order_Date'].dt.month #Extract the month feature.
df_encoded=df_encoded.drop(['Order_Date'], axis=1)
df_encoded

,Customer_ID,Order_ID,Quantity,City,District,Catalog_Number,Hebrew_Description,English_Description,Added_Date,Family_Item_ID,...,249,250,0,1,2,3,4,5,6,Month
0,100110,SO22000098,1,Ir ha-Karmel,חיפה,NHD1001-15-2,ינג כחול כיסוי 100% כותנה במילוי מיקרופייבר 40...,400GSM PREMIUM MICROFIBER BLANKET BLUE PIPING 15,5/31/2021,שמיכות,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4
1,100110,SO22000098,3,Ir ha-Karmel,חיפה,NHD1002-15-2,שמיכת פוך פייפינג כיסוי 100% כותנה מיקרופייבר ...,600GSM PREMIUM MICROFIBER BLANKET BLUE PIPING 15,5/31/2021,שמיכות,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4
2,100110,SO22000098,1,Ir ha-Karmel,חיפה,NHT3004-15-16,מגבת גוף אפור כהה 100% כותנה 600 גר' 90/150,Body towel 100% cotton Aqua Fibro 600 gsm 90x150,5/31/2021,מגבות,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4
3,100110,SO22000098,1,Ir ha-Karmel,חיפה,NHT3005-15-26,מגבת גוף טורקיז 100% כותנה 600 גר' 90/150,Body towel 100% cotton Aqua Fibro 600 gsm 90x150,5/31/2021,מגבות,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4
4,100110,SO22000098,1,Ir ha-Karmel,חיפה,NHT3006-15-23,מגבת פסים 150X90 כחול 600 גר',STRIPE TOWEL 150X90 BLUE 600 GSM,12/15/2021,מגבות,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9156,103230,SO23001622,1,Ashdod,דרום,NLW-71002M8,OCEAN M Mix&Match women tank,"Mix&Match women tank,,M",11/10/2021,7000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4
9157,103230,SO23001622,1,Ashdod,דרום,NLW-71003L6,-PEACH-L-Mix&Match women shorts,NaN,10/27/2021,7000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4
9158,103230,SO23001622,1,Ashdod,דרום,NLW-71003L8,-OCEAN-L-Mix&Match women shorts,NaN,10/27/2021,7000,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4
9159,103231,SO23001624,1,Kiryat-Motzkin,חיפה,NHB1006-16-13,"סט 100% כותנה סטן 220 160 סמ BASIC L. BLUE""",NaN,3/1/2022,220B,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4
9160,103231,SO23001624,1,Kiryat-Motzkin,חיפה,NHB1007-16-11,"סט 100% כותנה סטן 220 160 סמ BASIC SAND""",NaN,3/1/2022,220B,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4

In [18]:
df=df_encoded
from sklearn.preprocessing import LabelEncoder # Encode Categorical variables using LabelEncoder
label_encoder = LabelEncoder()
df['Customer_ID']= label_encoder.fit_transform(df['Customer_ID'])
df['Order_ID'] = label_encoder.fit_transform(df['Order_ID'])
df['Catalog_Number'] = label_encoder.fit_transform(df['Catalog_Number'])
df['Family_Item_ID'] = label_encoder.fit_transform(df['Family_Item_ID'])
df['Family_Item_Name'] = label_encoder.fit_transform(df['Family_Item_Name'])
df['Size'] = label_encoder.fit_transform(df['Size'])
df['Color_ID'] = label_encoder.fit_transform(df['Color_ID'])
df['Color_Name'] = label_encoder.fit_transform(df['Color_Name'])
df

,Customer_ID,Order_ID,Quantity,City,District,Catalog_Number,Hebrew_Description,English_Description,Added_Date,Family_Item_ID,...,249,250,0,1,2,3,4,5,6,Month
0,8,0,1,Ir ha-Karmel,חיפה,216,ינג כחול כיסוי 100% כותנה במילוי מיקרופייבר 40...,400GSM PREMIUM MICROFIBER BLANKET BLUE PIPING 15,5/31/2021,16,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4
1,8,0,3,Ir ha-Karmel,חיפה,219,שמיכת פוך פייפינג כיסוי 100% כותנה מיקרופייבר ...,600GSM PREMIUM MICROFIBER BLANKET BLUE PIPING 15,5/31/2021,16,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4
2,8,0,1,Ir ha-Karmel,חיפה,428,מגבת גוף אפור כהה 100% כותנה 600 גר' 90/150,Body towel 100% cotton Aqua Fibro 600 gsm 90x150,5/31/2021,10,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4
3,8,0,1,Ir ha-Karmel,חיפה,434,מגבת גוף טורקיז 100% כותנה 600 גר' 90/150,Body towel 100% cotton Aqua Fibro 600 gsm 90x150,5/31/2021,10,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4
4,8,0,1,Ir ha-Karmel,חיפה,440,מגבת פסים 150X90 כחול 600 גר',STRIPE TOWEL 150X90 BLUE 600 GSM,12/15/2021,10,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9156,2667,3337,1,Ashdod,דרום,584,OCEAN M Mix&Match women tank,"Mix&Match women tank,,M",11/10/2021,4,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4
9157,2667,3337,1,Ashdod,דרום,598,-PEACH-L-Mix&Match women shorts,NaN,10/27/2021,4,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4
9158,2667,3337,1,Ashdod,דרום,600,-OCEAN-L-Mix&Match women shorts,NaN,10/27/2021,4,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4
9159,2668,3339,1,Kiryat-Motzkin,חיפה,40,"סט 100% כותנה סטן 220 160 סמ BASIC L. BLUE""",NaN,3/1/2022,1,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4
9160,2668,3339,1,Kiryat-Motzkin,חיפה,44,"סט 100% כותנה סטן 220 160 סמ BASIC SAND""",NaN,3/1/2022,1,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4

In [19]:
# Calculate the count of orders per customer
df_customer_orders = df.groupby('Customer_ID')['Order_ID'].count().reset_index()
df_customer_orders = df_customer_orders.rename(columns={'Order_ID': 'Num_Orders'})
# Merge the derived feature back into the original DataFrame
df = pd.merge(df, df_customer_orders, on='Customer_ID', how='left')
df

,Customer_ID,Order_ID,Quantity,City,District,Catalog_Number,Hebrew_Description,English_Description,Added_Date,Family_Item_ID,...,250,0,1,2,3,4,5,6,Month,Num_Orders
0,8,0,1,Ir ha-Karmel,חיפה,216,ינג כחול כיסוי 100% כותנה במילוי מיקרופייבר 40...,400GSM PREMIUM MICROFIBER BLANKET BLUE PIPING 15,5/31/2021,16,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4,6
1,8,0,3,Ir ha-Karmel,חיפה,219,שמיכת פוך פייפינג כיסוי 100% כותנה מיקרופייבר ...,600GSM PREMIUM MICROFIBER BLANKET BLUE PIPING 15,5/31/2021,16,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4,6
2,8,0,1,Ir ha-Karmel,חיפה,428,מגבת גוף אפור כהה 100% כותנה 600 גר' 90/150,Body towel 100% cotton Aqua Fibro 600 gsm 90x150,5/31/2021,10,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4,6
3,8,0,1,Ir ha-Karmel,חיפה,434,מגבת גוף טורקיז 100% כותנה 600 גר' 90/150,Body towel 100% cotton Aqua Fibro 600 gsm 90x150,5/31/2021,10,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4,6
4,8,0,1,Ir ha-Karmel,חיפה,440,מגבת פסים 150X90 כחול 600 גר',STRIPE TOWEL 150X90 BLUE 600 GSM,12/15/2021,10,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9156,2667,3337,1,Ashdod,דרום,584,OCEAN M Mix&Match women tank,"Mix&Match women tank,,M",11/10/2021,4,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4,7
9157,2667,3337,1,Ashdod,דרום,598,-PEACH-L-Mix&Match women shorts,NaN,10/27/2021,4,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4,7
9158,2667,3337,1,Ashdod,דרום,600,-OCEAN-L-Mix&Match women shorts,NaN,10/27/2021,4,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4,7
9159,2668,3339,1,Kiryat-Motzkin,חיפה,40,"סט 100% כותנה סטן 220 160 סמ BASIC L. BLUE""",NaN,3/1/2022,1,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4,2
9160,2668,3339,1,Kiryat-Motzkin,חיפה,44,"סט 100% כותנה סטן 220 160 סמ BASIC SAND""",NaN,3/1/2022,1,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4,2

In [20]:
df_catalognumber_orders = df.groupby('Catalog_Number')['Order_ID'].count().reset_index()
df_catalognumber_orders = df_catalognumber_orders.rename(columns={'Order_ID': 'Count_Times_Articles_Appears'})
# Merge the derived feature back into the original DataFrame
df = pd.merge(df, df_catalognumber_orders, on='Catalog_Number', how='left')
df

,Customer_ID,Order_ID,Quantity,City,District,Catalog_Number,Hebrew_Description,English_Description,Added_Date,Family_Item_ID,...,0,1,2,3,4,5,6,Month,Num_Orders,Count_Times_Articles_Appears
0,8,0,1,Ir ha-Karmel,חיפה,216,ינג כחול כיסוי 100% כותנה במילוי מיקרופייבר 40...,400GSM PREMIUM MICROFIBER BLANKET BLUE PIPING 15,5/31/2021,16,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4,6,58
1,8,0,3,Ir ha-Karmel,חיפה,219,שמיכת פוך פייפינג כיסוי 100% כותנה מיקרופייבר ...,600GSM PREMIUM MICROFIBER BLANKET BLUE PIPING 15,5/31/2021,16,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4,6,65
2,8,0,1,Ir ha-Karmel,חיפה,428,מגבת גוף אפור כהה 100% כותנה 600 גר' 90/150,Body towel 100% cotton Aqua Fibro 600 gsm 90x150,5/31/2021,10,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4,6,29
3,8,0,1,Ir ha-Karmel,חיפה,434,מגבת גוף טורקיז 100% כותנה 600 גר' 90/150,Body towel 100% cotton Aqua Fibro 600 gsm 90x150,5/31/2021,10,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4,6,33
4,8,0,1,Ir ha-Karmel,חיפה,440,מגבת פסים 150X90 כחול 600 גר',STRIPE TOWEL 150X90 BLUE 600 GSM,12/15/2021,10,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4,6,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9156,2667,3337,1,Ashdod,דרום,584,OCEAN M Mix&Match women tank,"Mix&Match women tank,,M",11/10/2021,4,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4,7,13
9157,2667,3337,1,Ashdod,דרום,598,-PEACH-L-Mix&Match women shorts,NaN,10/27/2021,4,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4,7,5
9158,2667,3337,1,Ashdod,דרום,600,-OCEAN-L-Mix&Match women shorts,NaN,10/27/2021,4,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4,7,3
9159,2668,3339,1,Kiryat-Motzkin,חיפה,40,"סט 100% כותנה סטן 220 160 סמ BASIC L. BLUE""",NaN,3/1/2022,1,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4,2,10
9160,2668,3339,1,Kiryat-Motzkin,חיפה,44,"סט 100% כותנה סטן 220 160 סמ BASIC SAND""",NaN,3/1/2022,1,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4,2,31

In [21]:

df=df.drop(['Added_Date'],axis =1)
df=df.drop(['Hebrew_Description'],axis =1)
df=df.drop(['English_Description'],axis =1)
df=df.drop(['City'],axis=1)
df=df.drop(['District'],axis=1)
df

,Customer_ID,Order_ID,Quantity,Catalog_Number,Family_Item_ID,Family_Item_Name,Sales_Price_No_VAT,Sales_Price_With_VAT,Cost_Price,Cost_Import_USD,...,0,1,2,3,4,5,6,Month,Num_Orders,Count_Times_Articles_Appears
0,8,0,1,216,16,15,427,499,15,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4,6,58
1,8,0,3,219,16,15,469,549,17,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4,6,65
2,8,0,1,428,10,4,196,229,10,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4,6,29
3,8,0,1,434,10,4,196,229,10,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4,6,33
4,8,0,1,440,10,4,213,249,10,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4,6,19
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9156,2667,3337,1,584,4,1,102,119,5,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4,7,13
9157,2667,3337,1,598,4,1,110,129,5,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4,7,5
9158,2667,3337,1,600,4,1,110,129,5,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4,7,3
9159,2668,3339,1,40,1,10,512,599,28,28,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4,2,10
9160,2668,3339,1,44,1,10,512,599,28,28,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4,2,31

In [22]:
df.corr()['Sales_Price_With_VAT']

Customer_ID                    -0.028666
Order_ID                       -0.064587
Quantity                       -0.071621
Catalog_Number                 -0.345965
Family_Item_ID                 -0.053172
                                  ...
5                              -0.009389
6                              -0.001950
Month                           0.075072
Num_Orders                     -0.104880
Count_Times_Articles_Appears    0.085972
Name: Sales_Price_With_VAT, Length: 275, dtype: float64

In [23]:
df.corr()['Quantity']

Customer_ID                    -0.027668
Order_ID                       -0.017800
Quantity                        1.000000
Catalog_Number                 -0.053672
Family_Item_ID                  0.153018
                                  ...
5                              -0.010418
6                               0.022503
Month                           0.011745
Num_Orders                      0.000946
Count_Times_Articles_Appears    0.037236
Name: Quantity, Length: 275, dtype: float64

In [24]:
df.corr()['Family_Item_Name']

Customer_ID                    -0.078293
Order_ID                       -0.115198
Quantity                        0.083071
Catalog_Number                 -0.714568
Family_Item_ID                  0.070211
                                  ...
5                              -0.016777
6                               0.030428
Month                           0.194402
Num_Orders                     -0.071175
Count_Times_Articles_Appears    0.125043
Name: Family_Item_Name, Length: 275, dtype: float64

In [27]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Assuming your dataset is stored in a DataFrame called 'data'
# Splitting the data into features (X) and target variable (y)
X = df.drop(['Count_Times_Articles_Appears'], axis=1)
y = df['Count_Times_Articles_Appears']

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Creating the XGBoost regression model
model = xgb.XGBRegressor()

# Training the model
model.fit(X_train, y_train)

# Making predictions on the test set
y_pred = model.predict(X_test)
print(y_pred)

# Evaluating the model using mean squared error
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

ValueError: ignored

In [ ]:
df_pred = pd.DataFrame(y_pred)
df_pred

In [ ]:
import matplotlib.pyplot as plt
plt.scatter(y_test, y_pred, color='blue', alpha=0.5)
plt.plot([y_test.min(), y_test.max()], [y_pred.min(), y_pred.max()], color='red', linestyle='--')
plt.xlabel('Actual Quantity')
plt.ylabel('Predicted Quantity')
plt.title('Actual vs Predicted Quantity')
plt.show()