<a href="https://colab.research.google.com/github/Nlasry1996/Nautica-Home/blob/main/Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Connect To GitHub

In [ ]:
! git clone https://github.com/Nlasry1996/Nautica-Home.git # Connect to Github

fatal: destination path 'Nautica-Home' already exists and is not an empty directory.

Load Table

In [ ]:
import numpy as np
import pandas as pd
df=pd.read_csv('/content/Nautica-Home/NHDataset - NHDataset.csv')
df

,Order_Date,Customer_ID,Order_ID,Quantity,City,District,Catalog_Number,Hebrew_Description,English_Description,Added_Date,Family_Item_ID,Family_Item_Name,Sales_Price_No_VAT,Sales_Price_With_VAT,Cost_Price,Cost_Import_USD,Cost_Production_USD,Size,Color_ID,Color_Name
0,4/3/2022,100110,SO22000098,1,Ir ha-Karmel,חיפה,NHD1001-15-2,ינג כחול כיסוי 100% כותנה במילוי מיקרופייבר 40...,400GSM PREMIUM MICROFIBER BLANKET BLUE PIPING 15,5/31/2021,שמיכות,שמיכות,427,499,15,0,0,150/200,2,PAGEANT BLUE
1,4/3/2022,100110,SO22000098,3,Ir ha-Karmel,חיפה,NHD1002-15-2,שמיכת פוך פייפינג כיסוי 100% כותנה מיקרופייבר ...,600GSM PREMIUM MICROFIBER BLANKET BLUE PIPING 15,5/31/2021,שמיכות,שמיכות,469,549,17,0,0,150/200,2,PAGEANT BLUE
2,4/3/2022,100110,SO22000098,1,Ir ha-Karmel,חיפה,NHT3004-15-16,מגבת גוף אפור כהה 100% כותנה 600 גר' 90/150,Body towel 100% cotton Aqua Fibro 600 gsm 90x150,5/31/2021,מגבות,מגבות אקווה פיברו,196,229,10,0,0,90/150,16,Bruschetta
3,4/3/2022,100110,SO22000098,1,Ir ha-Karmel,חיפה,NHT3005-15-26,מגבת גוף טורקיז 100% כותנה 600 גר' 90/150,Body towel 100% cotton Aqua Fibro 600 gsm 90x150,5/31/2021,מגבות,מגבות אקווה פיברו,196,229,10,0,0,90/150,26,Peach Bud
4,4/3/2022,100110,SO22000098,1,Ir ha-Karmel,חיפה,NHT3006-15-23,מגבת פסים 150X90 כחול 600 גר',STRIPE TOWEL 150X90 BLUE 600 GSM,12/15/2021,מגבות,מגבות אקווה פיברו,213,249,10,0,0,150/90,23,China Blue
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9156,4/30/2023,103230,SO23001622,1,Ashdod,דרום,NLW-71002M8,OCEAN M Mix&Match women tank,"Mix&Match women tank,,M",11/10/2021,7000,Loungewear,102,119,5,0,5,M,8,Lolipop
9157,4/30/2023,103230,SO23001622,1,Ashdod,דרום,NLW-71003L6,-PEACH-L-Mix&Match women shorts,NaN,10/27/2021,7000,Loungewear,110,129,5,0,5,L,6,Cartouch
9158,4/30/2023,103230,SO23001622,1,Ashdod,דרום,NLW-71003L8,-OCEAN-L-Mix&Match women shorts,NaN,10/27/2021,7000,Loungewear,110,129,5,0,5,L,8,Lolipop
9159,4/30/2023,103231,SO23001624,1,Kiryat-Motzkin,חיפה,NHB1006-16-13,"סט 100% כותנה סטן 220 160 סמ BASIC L. BLUE""",NaN,3/1/2022,220B,סאטן 220 בסיק,512,599,28,28,0,160/200,13,L. PINK
9160,4/30/2023,103231,SO23001624,1,Kiryat-Motzkin,חיפה,NHB1007-16-11,"סט 100% כותנה סטן 220 160 סמ BASIC SAND""",NaN,3/1/2022,220B,סאטן 220 בסיק,512,599,28,28,0,160/200,11,GOLD

In [ ]:
df['Order_Date'] = pd.to_datetime(df['Order_Date']) # Convert 'Order_Date' to a datetime format.
df['Month'] = df['Order_Date'].dt.month #Extract the month feature.
df=df.drop(['Order_Date'], axis=1)

from sklearn.preprocessing import LabelEncoder # Encode Categorical variables using LabelEncoder
label_encoder = LabelEncoder()
df['Customer_ID']= label_encoder.fit_transform(df['Customer_ID'])
df['Order_ID'] = label_encoder.fit_transform(df['Order_ID'])
df['Catalog_Number'] = label_encoder.fit_transform(df['Catalog_Number'])
df['City'] = label_encoder.fit_transform(df['City'])
df['District'] = label_encoder.fit_transform(df['District'])
df['Family_Item_ID'] = label_encoder.fit_transform(df['Family_Item_ID'])
df['Family_Item_Name'] = label_encoder.fit_transform(df['Family_Item_Name'])
df['Size'] = label_encoder.fit_transform(df['Size'])
df['Color_ID'] = label_encoder.fit_transform(df['Color_ID'])
df['Color_Name'] = label_encoder.fit_transform(df['Color_Name'])
df

,Customer_ID,Order_ID,Quantity,City,District,Catalog_Number,Hebrew_Description,English_Description,Added_Date,Family_Item_ID,Family_Item_Name,Sales_Price_No_VAT,Sales_Price_With_VAT,Cost_Price,Cost_Import_USD,Cost_Production_USD,Size,Color_ID,Color_Name,Month
0,8,0,1,77,2,216,ינג כחול כיסוי 100% כותנה במילוי מיקרופייבר 40...,400GSM PREMIUM MICROFIBER BLANKET BLUE PIPING 15,5/31/2021,16,15,427,499,15,0,0,4,1,24,4
1,8,0,3,77,2,219,שמיכת פוך פייפינג כיסוי 100% כותנה מיקרופייבר ...,600GSM PREMIUM MICROFIBER BLANKET BLUE PIPING 15,5/31/2021,16,15,469,549,17,0,0,4,1,24,4
2,8,0,1,77,2,428,מגבת גוף אפור כהה 100% כותנה 600 גר' 90/150,Body towel 100% cotton Aqua Fibro 600 gsm 90x150,5/31/2021,10,4,196,229,10,0,0,21,14,2,4
3,8,0,1,77,2,434,מגבת גוף טורקיז 100% כותנה 600 גר' 90/150,Body towel 100% cotton Aqua Fibro 600 gsm 90x150,5/31/2021,10,4,196,229,10,0,0,21,21,28,4
4,8,0,1,77,2,440,מגבת פסים 150X90 כחול 600 גר',STRIPE TOWEL 150X90 BLUE 600 GSM,12/15/2021,10,4,213,249,10,0,0,5,18,6,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9156,2667,3337,1,11,1,584,OCEAN M Mix&Match women tank,"Mix&Match women tank,,M",11/10/2021,4,1,102,119,5,0,5,24,7,18,4
9157,2667,3337,1,11,1,598,-PEACH-L-Mix&Match women shorts,NaN,10/27/2021,4,1,110,129,5,0,5,23,5,4,4
9158,2667,3337,1,11,1,600,-OCEAN-L-Mix&Match women shorts,NaN,10/27/2021,4,1,110,129,5,0,5,23,7,18,4
9159,2668,3339,1,111,2,40,"סט 100% כותנה סטן 220 160 סמ BASIC L. BLUE""",NaN,3/1/2022,1,10,512,599,28,28,0,6,12,17,4
9160,2668,3339,1,111,2,44,"סט 100% כותנה סטן 220 160 סמ BASIC SAND""",NaN,3/1/2022,1,10,512,599,28,28,0,6,10,12,4

In [ ]:
# Calculate the count of orders per customer
df_customer_orders = df.groupby('Customer_ID')['Order_ID'].count().reset_index()
df_customer_orders = df_customer_orders.rename(columns={'Order_ID': 'Num_Orders'})
# Merge the derived feature back into the original DataFrame
df = pd.merge(df, df_customer_orders, on='Customer_ID', how='left')

df_catalognumber_orders = df.groupby('Catalog_Number')['Order_ID'].count().reset_index()
df_catalognumber_orders = df_catalognumber_orders.rename(columns={'Order_ID': 'Count_Times_Articles_Appears'})
# Merge the derived feature back into the original DataFrame
df = pd.merge(df, df_catalognumber_orders, on='Catalog_Number', how='left')

df_family_item_orders = df.groupby('Family_Item_Name')['Order_ID'].count().reset_index()
df_family_item_orders = df_family_item_orders.rename(columns={'Order_ID': 'Number_FI_per_Year'})
# Merge the derived feature back into the original DataFrame
df = pd.merge(df, df_family_item_orders, on='Family_Item_Name', how='left')
df

,Customer_ID,Order_ID,Quantity,City,District,Catalog_Number,Hebrew_Description,English_Description,Added_Date,Family_Item_ID,...,Cost_Price,Cost_Import_USD,Cost_Production_USD,Size,Color_ID,Color_Name,Month,Num_Orders,Count_Times_Articles_Appears,Number_FI_per_Year
0,8,0,1,77,2,216,ינג כחול כיסוי 100% כותנה במילוי מיקרופייבר 40...,400GSM PREMIUM MICROFIBER BLANKET BLUE PIPING 15,5/31/2021,16,...,15,0,0,4,1,24,4,6,58,371
1,8,0,3,77,2,219,שמיכת פוך פייפינג כיסוי 100% כותנה מיקרופייבר ...,600GSM PREMIUM MICROFIBER BLANKET BLUE PIPING 15,5/31/2021,16,...,17,0,0,4,1,24,4,6,65,371
2,8,0,1,77,2,428,מגבת גוף אפור כהה 100% כותנה 600 גר' 90/150,Body towel 100% cotton Aqua Fibro 600 gsm 90x150,5/31/2021,10,...,10,0,0,21,14,2,4,6,29,984
3,8,0,1,77,2,434,מגבת גוף טורקיז 100% כותנה 600 גר' 90/150,Body towel 100% cotton Aqua Fibro 600 gsm 90x150,5/31/2021,10,...,10,0,0,21,21,28,4,6,33,984
4,8,0,1,77,2,440,מגבת פסים 150X90 כחול 600 גר',STRIPE TOWEL 150X90 BLUE 600 GSM,12/15/2021,10,...,10,0,0,5,18,6,4,6,19,984
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9156,2667,3337,1,11,1,584,OCEAN M Mix&Match women tank,"Mix&Match women tank,,M",11/10/2021,4,...,5,0,5,24,7,18,4,7,13,2786
9157,2667,3337,1,11,1,598,-PEACH-L-Mix&Match women shorts,NaN,10/27/2021,4,...,5,0,5,23,5,4,4,7,5,2786
9158,2667,3337,1,11,1,600,-OCEAN-L-Mix&Match women shorts,NaN,10/27/2021,4,...,5,0,5,23,7,18,4,7,3,2786
9159,2668,3339,1,111,2,40,"סט 100% כותנה סטן 220 160 סמ BASIC L. BLUE""",NaN,3/1/2022,1,...,28,28,0,6,12,17,4,2,10,618
9160,2668,3339,1,111,2,44,"סט 100% כותנה סטן 220 160 סמ BASIC SAND""",NaN,3/1/2022,1,...,28,28,0,6,10,12,4,2,31,618

In [ ]:
df['Family_Item_Count_Monthly'] = df.groupby(['Month', 'Family_Item_ID'])['Order_ID'].transform('count')
df

,Customer_ID,Order_ID,Quantity,City,District,Catalog_Number,Hebrew_Description,English_Description,Added_Date,Family_Item_ID,...,Cost_Import_USD,Cost_Production_USD,Size,Color_ID,Color_Name,Month,Num_Orders,Count_Times_Articles_Appears,Number_FI_per_Year,Family_Item_Count_Monthly
0,8,0,1,77,2,216,ינג כחול כיסוי 100% כותנה במילוי מיקרופייבר 40...,400GSM PREMIUM MICROFIBER BLANKET BLUE PIPING 15,5/31/2021,16,...,0,0,4,1,24,4,6,58,371,36
1,8,0,3,77,2,219,שמיכת פוך פייפינג כיסוי 100% כותנה מיקרופייבר ...,600GSM PREMIUM MICROFIBER BLANKET BLUE PIPING 15,5/31/2021,16,...,0,0,4,1,24,4,6,65,371,36
2,8,0,1,77,2,428,מגבת גוף אפור כהה 100% כותנה 600 גר' 90/150,Body towel 100% cotton Aqua Fibro 600 gsm 90x150,5/31/2021,10,...,0,0,21,14,2,4,6,29,984,140
3,8,0,1,77,2,434,מגבת גוף טורקיז 100% כותנה 600 גר' 90/150,Body towel 100% cotton Aqua Fibro 600 gsm 90x150,5/31/2021,10,...,0,0,21,21,28,4,6,33,984,140
4,8,0,1,77,2,440,מגבת פסים 150X90 כחול 600 גר',STRIPE TOWEL 150X90 BLUE 600 GSM,12/15/2021,10,...,0,0,5,18,6,4,6,19,984,140
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9156,2667,3337,1,11,1,584,OCEAN M Mix&Match women tank,"Mix&Match women tank,,M",11/10/2021,4,...,0,5,24,7,18,4,7,13,2786,248
9157,2667,3337,1,11,1,598,-PEACH-L-Mix&Match women shorts,NaN,10/27/2021,4,...,0,5,23,5,4,4,7,5,2786,248
9158,2667,3337,1,11,1,600,-OCEAN-L-Mix&Match women shorts,NaN,10/27/2021,4,...,0,5,23,7,18,4,7,3,2786,248
9159,2668,3339,1,111,2,40,"סט 100% כותנה סטן 220 160 סמ BASIC L. BLUE""",NaN,3/1/2022,1,...,28,0,6,12,17,4,2,10,618,78
9160,2668,3339,1,111,2,44,"סט 100% כותנה סטן 220 160 סמ BASIC SAND""",NaN,3/1/2022,1,...,28,0,6,10,12,4,2,31,618,78

In [ ]:
df=df.drop(['Added_Date','Customer_ID','Order_ID','City',	'District','Hebrew_Description','English_Description','Cost_Import_USD'	,'Cost_Production_USD','Size','Color_ID','Color_Name'], axis=1)

df

,Quantity,Catalog_Number,Family_Item_ID,Family_Item_Name,Sales_Price_No_VAT,Sales_Price_With_VAT,Cost_Price,Month,Num_Orders,Count_Times_Articles_Appears,Number_FI_per_Year,Family_Item_Count_Monthly
0,1,216,16,15,427,499,15,4,6,58,371,36
1,3,219,16,15,469,549,17,4,6,65,371,36
2,1,428,10,4,196,229,10,4,6,29,984,140
3,1,434,10,4,196,229,10,4,6,33,984,140
4,1,440,10,4,213,249,10,4,6,19,984,140
...,...,...,...,...,...,...,...,...,...,...,...,...
9156,1,584,4,1,102,119,5,4,7,13,2786,248
9157,1,598,4,1,110,129,5,4,7,5,2786,248
9158,1,600,4,1,110,129,5,4,7,3,2786,248
9159,1,40,1,10,512,599,28,4,2,10,618,78
9160,1,44,1,10,512,599,28,4,2,31,618,78

In [7]:
df.corr()['Family_Item_Count_Monthly']

Quantity                       -0.126853
Catalog_Number                  0.453630
Family_Item_ID                 -0.235095
Family_Item_Name               -0.472360
Sales_Price_No_VAT             -0.199782
Sales_Price_With_VAT           -0.199685
Cost_Price                     -0.186110
Month                          -0.417169
Num_Orders                      0.020691
Count_Times_Articles_Appears   -0.218558
Number_FI_per_Year              0.657557
Family_Item_Count_Monthly       1.000000
Name: Family_Item_Count_Monthly, dtype: float64